spring.application.name=securevoting

spring.datasource.url=jdbc:mysql://localhost:3306/securevoting?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Mayuri9870@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# Root logging level
logging.level.root=INFO

# Spring Web debug logs
logging.level.org.springframework.web=DEBUG

# Your project package debug logs
logging.level.com.evoting.securevoting=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jadhavmayuri9870@gmail.com
spring.mail.password=bnezyfvoqftzdznr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true